(function(e){var A=e.Chart,y=e.addEvent,D=e.removeEvent,p=e.createElement,l=e.discardElement,x=e.css,m=e.merge,v=e.each,t=e.extend,E=Math.max,k=document,B=window,F=e.isTouchDevice,G=e.Renderer.prototype.symbols,w=e.getOptions(),q;t(w.lang,{printChart:"Print chart",downloadPNG:"Download PNG image",downloadJPEG:"Download JPEG image",downloadPDF:"Download PDF document",downloadSVG:"Download SVG vector image",contextButtonTitle:"Chart context menu"});w.navigation={menuStyle:{border:"1px solid #A0A0A0",
background:"#FFFFFF",padding:"5px 0"},menuItemStyle:{padding:"0 10px",background:"none",color:"#303030",fontSize:F?"14px":"11px"},menuItemHoverStyle:{background:"#4572A5",color:"#FFFFFF"},buttonOptions:{symbolFill:"#E0E0E0",symbolSize:14,symbolStroke:"#666",symbolStrokeWidth:3,symbolX:12.5,symbolY:10.5,align:"right",buttonSpacing:3,height:22,theme:{fill:"white",stroke:"none"},verticalAlign:"top",width:24}};w.exporting={type:"image/png",url:"http://export.highcharts.com/",buttons:{contextButton:{symbol:"menu",
_titleKey:"contextButtonTitle",menuItems:[{textKey:"printChart",onclick:function(){this.print()}},{separator:!0},{textKey:"downloadPNG",onclick:function(){this.exportChart()}},{textKey:"downloadJPEG",onclick:function(){this.exportChart({type:"image/jpeg"})}},{textKey:"downloadPDF",onclick:function(){this.exportChart({type:"application/pdf"})}},{textKey:"downloadSVG",onclick:function(){this.exportChart({type:"image/svg+xml"})}}]}}};e.post=function(a,b){var c,d;d=p("form",{method:"post",action:a,enctype:"multipart/form-data"},
{display:"none"},k.body);for(c in b)p("input",{type:"hidden",name:c,value:b[c]},null,d);d.submit();l(d)};t(A.prototype,{getSVG:function(a){var b=this,c,d,z,g,f=m(b.options,a);k.createElementNS||(k.createElementNS=function(a,b){return k.createElement(b)});a=p("div",null,{position:"absolute",top:"-9999em",width:b.chartWidth+"px",height:b.chartHeight+"px"},k.body);d=b.renderTo.style.width;g=b.renderTo.style.height;d=f.exporting.sourceWidth||f.chart.width||/px$/.test(d)&&parseInt(d,10)||600;g=f.exporting.sourceHeight||
f.chart.height||/px$/.test(g)&&parseInt(g,10)||400;t(f.chart,{animation:!1,renderTo:a,forExport:!0,width:d,height:g});f.exporting.enabled=!1;f.chart.plotBackgroundImage=null;f.series=[];v(b.series,function(a){z=m(a.options,{animation:!1,showCheckbox:!1,visible:a.visible});z.isInternal||f.series.push(z)});c=new e.Chart(f,b.callback);v(["xAxis","yAxis"],function(a){v(b[a],function(b,d){var f=c[a][d],e=b.getExtremes(),g=e.userMin,e=e.userMax;void 0===g&&void 0===e||f.setExtremes(g,e,!0,!1)})});d=c.container.innerHTML;
f=null;c.destroy();l(a);d=d.replace(/zIndex="[^"]+"/g,"").replace(/isShadow="[^"]+"/g,"").replace(/symbolName="[^"]+"/g,"").replace(/jQuery[0-9]+="[^"]+"/g,"").replace(/url\([^#]+#/g,"url(#").replace(/<svg /,'<svg xmlns:xlink="http://www.w3.org/1999/xlink" ').replace(/ href=/g," xlink:href=").replace(/\n/," ").replace(/<\/svg>.*?$/,"</svg>").replace(/&nbsp;/g,"\u00a0").replace(/&shy;/g,"\u00ad").replace(/<IMG /g,"<image ").replace(/height=([^" ]+)/g,'height="$1"').replace(/width=([^" ]+)/g,'width="$1"').replace(/hc-svg-href="([^"]+)">/g,
'xlink:href="$1"/>').replace(/id=([^" >]+)/g,'id="$1"').replace(/class=([^" ]+)/g,'class="$1"').replace(/ transform /g," ").replace(/:(path|rect)/g,"$1").replace(/style="([^"]+)"/g,function(a){return a.toLowerCase()});d=d.replace(/(url\(#highcharts-[0-9]+)&quot;/g,"$1").replace(/&quot;/g,"'");2===d.match(/ xmlns="/g).length&&(d=d.replace(/xmlns="[^"]+"/,""));return d},exportChart:function(a,b){a=a||{};var c=this.options.exporting,c=this.getSVG(m({chart:{borderRadius:0}},c,b,{exporting:{sourceWidth:a.sourceWidth||
c.sourceWidth,sourceHeight:a.sourceHeight||c.sourceHeight}}));a=m(this.options.exporting,a);e.post(a.url,{filename:a.filename||"chart",type:a.type,width:a.width||0,scale:a.scale||2,svg:c})},print:function(){var a=this,b=a.container,c=[],d=b.parentNode,e=k.body,g=e.childNodes;a.isPrinting||(a.isPrinting=!0,v(g,function(a,b){1===a.nodeType&&(c[b]=a.style.display,a.style.display="none")}),e.appendChild(b),B.focus(),B.print(),setTimeout(function(){d.appendChild(b);v(g,function(a,b){1===a.nodeType&&(a.style.display=
c[b])});a.isPrinting=!1},1E3))},contextMenu:function(a,b,c,d,e,g,f){var h=this,u=h.options.navigation,r=u.menuItemStyle,s=h.chartWidth,k=h.chartHeight,C="cache-"+a,n=h[C],m=E(e,g),q,l,w;n||(h[C]=n=p("div",{className:"highcharts-"+a},{position:"absolute",zIndex:1E3,padding:m+"px"},h.container),q=p("div",null,t({MozBoxShadow:"3px 3px 10px #888",WebkitBoxShadow:"3px 3px 10px #888",boxShadow:"3px 3px 10px #888"},u.menuStyle),n),l=function(){x(n,{display:"none"});f&&f.setState(0)},y(n,"mouseleave",function(){w=
setTimeout(l,500)}),y(n,"mouseenter",function(){clearTimeout(w)}),v(b,function(a){if(a){var b=a.separator?p("hr",null,null,q):p("div",{onmouseover:function(){x(this,u.menuItemHoverStyle)},onmouseout:function(){x(this,r)},onclick:function(){l();a.onclick.apply(h,arguments)},innerHTML:a.text||h.options.lang[a.textKey]},t({cursor:"pointer"},r),q);h.exportDivElements.push(b)}}),h.exportDivElements.push(q,n),h.exportMenuWidth=n.offsetWidth,h.exportMenuHeight=n.offsetHeight);a={display:"block"};c+h.exportMenuWidth>
s?a.right=s-c-e-m+"px":a.left=c-m+"px";d+g+h.exportMenuHeight>k?a.bottom=k-d-m+"px":a.top=d+g-m+"px";x(n,a)},addButton:function(a){var b=this,c=b.renderer;a=m(b.options.navigation.buttonOptions,a);var d=a.onclick,k=a.menuItems,g,f,h={stroke:a.symbolStroke,fill:a.symbolFill},u=a.symbolSize||12;b.btnCount||(b.btnCount=0);b.btnCount++;b.exportDivElements||(b.exportDivElements=[],b.exportSVGElements=[]);if(!1!==a.enabled){var r=a.theme,s=r.states,p=s&&s.hover,s=s&&s.select,l;delete r.states;d?l=function(){d.apply(b,
arguments)}:k&&(l=function(){b.contextMenu("contextmenu",k,f.translateX,f.translateY,f.width,f.height,f);f.setState(2)});a.text&&a.symbol?r.paddingLeft=e.pick(r.paddingLeft,25):a.text||t(r,{width:a.width,height:a.height,padding:0});f=c.button(a.text,0,0,l,r,p,s).attr({title:b.options.lang[a._titleKey],"stroke-linecap":"round"});a.symbol&&(g=c.symbol(a.symbol,a.symbolX-u/2,a.symbolY-u/2,u,u).attr(t(h,{"stroke-width":a.symbolStrokeWidth||1,zIndex:1})).add(f));f.add().align(t(a,{width:f.width,x:e.pick(a.x,
q)}),!0,"spacingBox");q+=(f.width+a.buttonSpacing)*("right"===a.align?-1:1);b.exportSVGElements.push(f,g)}},destroyExport:function(a){a=a.target;var b,c;for(b=0;b<a.exportSVGElements.length;b++)c=a.exportSVGElements[b],c.onclick=c.ontouchstart=null,a.exportSVGElements[b]=c.destroy();for(b=0;b<a.exportDivElements.length;b++)c=a.exportDivElements[b],D(c,"mouseleave"),a.exportDivElements[b]=c.onmouseout=c.onmouseover=c.ontouchstart=c.onclick=null,l(c)}});G.menu=function(a,b,c,d){return["M",a,b+2.5,"L",
a+c,b+2.5,"M",a,b+d/2+0.5,"L",a+c,b+d/2+0.5,"M",a,b+d-1.5,"L",a+c,b+d-1.5]};A.prototype.callbacks.push(function(a){var b,c=a.options.exporting,d=c.buttons;q=0;if(!1!==c.enabled){for(b in d)a.addButton(d[b]);y(a,"destroy",a.destroyExport)}})})(Highcharts);
