var CodeMirror=function(){function r(a,b){function d(a){return 0<=a&&a<t.size}function f(a){for(var s=t;!s.lines;)for(var m=0;;++m){var b=s.children[m],d=b.chunkSize();if(a<d){s=b;break}a-=d}return s.lines[a]}function k(a,s){pa=!0;for(var m=s-a.height,b=a;b;b=b.parent)b.height+=m}function n(a){var s={line:0,ch:0};Kb(s,{line:t.size-1,ch:f(t.size-1).text.length},e(a),s,s);ya=!0}function u(a){var s=B[a.keyCode],m=aa[p.keyMap].auto,b,d;if(null==s||a.altGraphKey)return m&&(p.keyMap=m),null;a.altKey&&(s=
"Alt-"+s);a.ctrlKey&&(s="Ctrl-"+s);a.metaKey&&(s="Cmd-"+s);a.shiftKey&&(b=O("Shift-"+s,p.extraKeys,p.keyMap))?d=!0:b=O(s,p.extraKeys,p.keyMap);"string"==typeof b&&(b=Ma.propertyIsEnumerable(b)?Ma[b]:null);(s=m)&&!(s=b)&&(s=B[a.keyCode],s=!("Ctrl"==s||"Alt"==s||"Shift"==s||"Mod"==s));s&&(p.keyMap=m);if(!b)return!1;d?(m=la,la=null,b(P),la=m):b(P);v(a);return!0}function h(){if(!p.readOnly){if(!ma){if(p.onFocus)p.onFocus(P);ma=!0;-1==Q.className.search(/\bCodeMirror-focused\b/)&&(Q.className+=" CodeMirror-focused");
Ra||ob(!0)}db();Lb()}}function N(){if(ma){if(p.onBlur)p.onBlur(P);ma=!1;Q.className=Q.className.replace(" CodeMirror-focused","")}clearInterval(pb);setTimeout(function(){ma||(la=null)},150)}function Kb(a,s,m,b,d){if(na){var f=[];t.iter(a.line,s.line+1,function(a){f.push(a.text)});for(na.addChange(a.line,m.length,f);na.done.length>p.undoDepth;)na.done.shift()}U(a,s,m,b,d)}function M(a,s){var m=a.pop();if(m){var b=[],d=m.start+m.added;t.iter(m.start,d,function(a){b.push(a.text)});s.push({start:m.start,
added:m.old.length,old:b});var k=V({line:m.start+m.old.length-1,ch:qb(b[b.length-1],m.old[m.old.length-1])});U({line:m.start,ch:0},{line:d-1,ch:f(d-1).text.length},m.old,k,k);ya=!0}}function U(a,s,b,d,kc){var e=!1,c=za.length;p.lineWrapping||t.iter(a.line,s.line,function(a){if(a.text.length==c)return e=!0});if(a.line!=s.line||1<b.length)pa=!0;var ea=s.line-a.line,n=f(a.line),u=f(s.line);if(0==a.ch&&0==s.ch&&""==b[b.length-1]){var g=[],n=null;a.line?(n=f(a.line-1),n.fixMarkEnds(u)):u.fixMarkStarts();
for(var h=0,A=b.length-1;h<A;++h)g.push(z.inheritMarks(b[h],n));ea&&t.remove(a.line,ea,Sa);g.length&&t.insert(a.line,g)}else if(n==u)if(1==b.length)n.replace(a.ch,s.ch,b[0]);else{u=n.split(s.ch,b[b.length-1]);n.replace(a.ch,null,b[0]);n.fixMarkEnds(u);g=[];h=1;for(A=b.length-1;h<A;++h)g.push(z.inheritMarks(b[h],n));g.push(u);t.insert(a.line+1,g)}else if(1==b.length)n.replace(a.ch,null,b[0]),u.replace(null,s.ch,""),n.append(u),t.remove(a.line+1,ea,Sa);else{g=[];n.replace(a.ch,null,b[0]);u.replace(null,
s.ch,b[b.length-1]);n.fixMarkEnds(u);h=1;for(A=b.length-1;h<A;++h)g.push(z.inheritMarks(b[h],n));1<ea&&t.remove(a.line+1,ea-1,Sa);t.insert(a.line+1,g)}if(p.lineWrapping){var B=y.clientWidth/rb()-3;t.iter(a.line,a.line+b.length,function(a){if(!a.hidden){var D=Math.ceil(a.text.length/B)||1;D!=a.height&&k(a,D)}})}else t.iter(a.line,h+b.length,function(a){a=a.text;a.length>c&&(za=a,c=a.length,Aa=null,e=!1)}),e&&(c=0,za="",Aa=null,t.iter(0,t.size,function(a){a=a.text;a.length>c&&(c=a.length,za=a)}));u=
[];ea=b.length-ea-1;h=0;for(g=qa.length;h<g;++h)A=qa[h],A<a.line?u.push(A):A>s.line&&u.push(A+ea);h=a.line+Math.min(b.length,500);lc(a.line,h);u.push(h);qa=u;sb(100);Y.push({from:a.line,to:s.line+1,diff:ea});a={from:a,to:s,text:b};if(Ta){for(b=Ta;b.next;b=b.next);b.next=a}else Ta=a;Ua(d,kc,l.from.line<=Math.min(s.line,s.line+ea)?l.from.line:l.from.line+ea,l.to.line<=Math.min(s.line,s.line+ea)?l.to.line:l.to.line+ea);fa.style.height=t.height*wa()+2*I.offsetTop+"px"}function ra(a,b,m){function d(La){if(ha(La,
b))return La;if(!ha(m,La))return f;var k=La.line+a.length-(m.line-b.line)-1,e=La.ch;La.line==m.line&&(e+=a[a.length-1].length-(m.ch-(m.line==b.line?b.ch:0)));return{line:k,ch:e}}b=V(b);m=m?V(m):b;a=e(a);var f;Mb(a,b,m,function(a){f=a;return{from:d(l.from),to:d(l.to)}});return f}function X(a,b){Mb(e(a),l.from,l.to,function(a){return"end"==b?{from:a,to:a}:"start"==b?{from:l.from,to:l.from}:{from:l.from,to:a}})}function Mb(a,b,m,d){d=d({line:b.line+a.length-1,ch:1==a.length?a[0].length+b.ch:a[a.length-
1].length});Kb(b,m,a,d.from,d.to)}function da(a,b){var m=a.line,d=b.line;if(m==d)return f(m).text.slice(a.ch,b.ch);var k=[f(m).text.slice(a.ch)];t.iter(m+1,d,function(a){k.push(a.text)});k.push(f(d).text.slice(0,b.ch));return k.join("\n")}function eb(){return da(l.from,l.to)}function db(){tb||ub.set(p.pollInterval,function(){vb();va();ma&&db();wb()})}function Va(){function a(){vb();va()||b?(tb=!1,db()):(b=!0,ub.set(60,a));wb()}var b=!1;tb=!0;ub.set(20,a)}function va(){if(Ra||!ma||J(H))return!1;var a=
H.value;if(a==Ba)return!1;la=null;for(var b=0,m=Math.min(Ba.length,a.length);b<m&&Ba[b]==a[b];)++b;b<Ba.length?l.from={line:l.from.line,ch:l.from.ch-(Ba.length-b)}:xb&&q(l.from,l.to)&&(l.to={line:l.to.line,ch:Math.min(f(l.to.line).text.length,l.to.ch+(a.length-b))});X(a.slice(b),"end");Ba=a;return!0}function ob(a){q(l.from,l.to)?a&&(Ba=H.value=""):(Ba="",H.value=eb(),H.select())}function Ha(){p.readOnly||H.focus()}function mc(){if(sa.getBoundingClientRect){var a=sa.getBoundingClientRect();if(!Ca||
a.top!=a.bottom){var b=window.innerHeight||Math.max(document.body.offsetHeight,document.documentElement.offsetHeight);(0>a.top||a.bottom>b)&&sa.scrollIntoView()}}}function Nb(){var a=Wa(l.inverted?l.from:l.to),b=p.lineWrapping?Math.min(a.x,I.offsetWidth):a.x;return Ob(b,a.y,b,a.yBot)}function Ob(a,b,m,d){var f=I.offsetLeft,k=I.offsetTop,e=wa();b+=k;d+=k;a+=f;m+=f;var c=y.clientHeight,l=y.scrollTop,f=!1,k=!0;b<l?(y.scrollTop=Math.max(0,b-2*e),f=!0):d>l+c&&(y.scrollTop=d+e-c,f=!0);b=y.clientWidth;d=
y.scrollLeft;e=p.fixedGutter?ca.clientWidth:0;a<d+e?(50>a&&(a=0),y.scrollLeft=Math.max(0,a-10-e),f=!0):m>b+d-3&&(y.scrollLeft=m+10-b,f=!0,m>fa.clientWidth&&(k=!1));if(f&&p.onScroll)p.onScroll(P);return k}function Pb(){var a=wa(),b=y.scrollTop-I.offsetTop,m=Math.max(0,Math.floor(b/a)),a=Math.ceil((b+y.clientHeight)/a);return{from:oa(t,m),to:oa(t,a)}}function Xa(a,b){if(y.clientWidth){var m=Pb();if(!(!0!==a&&0==a.length&&m.from>=Z&&m.to<=ia)){var d=Math.max(m.from-100,0),m=Math.min(t.size,m.to+100);
Z<d&&20>d-Z&&(d=Z);ia>m&&20>ia-m&&(m=Math.min(t.size,ia));for(var f=!0===a?[]:nc([{from:Z,to:ia,domStart:0}],a),e=0,c=0;c<f.length;++c){var l=f[c];l.from<d&&(l.domStart+=d-l.from,l.from=d);l.to>m&&(l.to=m);l.from>=l.to?f.splice(c--,1):e+=l.to-l.from}if(e!=m-d){f.sort(function(a,D){return a.domStart-D.domStart});var n=wa(),e=ca.style.display;ja.style.display=ca.style.display="none";oc(d,m,f);ja.style.display="";(c=d!=Z||m!=ia||Qb!=y.clientHeight+n)&&(Qb=y.clientHeight+n);Z=d;ia=m;Ya=L(t,d);fb.style.top=
Ya*n+"px";fa.style.height=t.height*n+2*I.offsetTop+"px";if(ja.childNodes.length!=ia-Z)throw Error("BAD PATCH! "+JSON.stringify(f)+" size="+(ia-Z)+" nodes="+ja.childNodes.length);if(p.lineWrapping){Aa=y.clientWidth;var u=ja.firstChild;t.iter(Z,ia,function(a){if(!a.hidden){var D=Math.round(u.offsetHeight/n)||1;a.height!=D&&(k(a,D),pa=!0)}u=u.nextSibling})}else null==Aa&&(Aa=yb(za)),Aa>y.clientWidth?(I.style.width=Aa+"px",fa.style.width="",fa.style.width=y.scrollWidth+"px"):I.style.width=fa.style.width=
"";ca.style.display=e;(c||pa)&&Rb();Sb();if(!b&&p.onUpdate)p.onUpdate(P);return!0}}}else Z=ia=Ya=0}function nc(a,b){for(var m=0,d=b.length||0;m<d;++m){for(var f=b[m],k=[],e=f.diff||0,c=0,l=a.length;c<l;++c){var n=a[c];f.to<=n.from&&f.diff?k.push({from:n.from+e,to:n.to+e,domStart:n.domStart}):f.to<=n.from||f.from>=n.to?k.push(n):(f.from>n.from&&k.push({from:n.from,to:f.from,domStart:n.domStart}),f.to<n.to&&k.push({from:f.to+e,to:n.to+e,domStart:n.domStart+(f.to-n.from)}))}a=k}return a}function oc(a,
b,m){if(m.length){for(var d=function(a){var D=a.nextSibling;a.parentNode.removeChild(a);return D},f=0,k=ja.firstChild,e=0;e<m.length;++e){for(var c=m[e];c.domStart>f;)k=d(k),f++;for(var n=0,c=c.to-c.from;n<c;++n)k=k.nextSibling,f++}for(;k;)k=d(k)}else ja.innerHTML="";var u=m.shift(),k=ja.firstChild,n=a,g=l.from.line,h=l.to.line,p=g<a&&h>=a,A=Ia.createElement("div");t.iter(a,b,function(a){var D=null,b=null;p?(D=0,h==n&&(p=!1,b=l.to.ch)):g==n&&(h==n?(D=l.from.ch,b=l.to.ch):(p=!0,D=l.from.ch));u&&u.to==
n&&(u=m.shift());!u||u.from>n?(A.innerHTML=a.hidden?"<pre></pre>":a.getHTML(D,b,!0,zb),ja.insertBefore(A.firstChild,k)):k=k.nextSibling;++n})}function Rb(){if(p.gutter||p.lineNumbers){var a=fb.offsetHeight,b=y.clientHeight;ca.style.height=(2>a-b?b:a)+"px";var m=[],d=Z;t.iter(Z,Math.max(ia,Z+1),function(a){if(a.hidden)m.push("<pre></pre>");else{var b=a.gutterMarker,D=p.lineNumbers?d+p.firstLineNumber:null;b&&b.text?D=b.text.replace("%N%",null!=D?D:""):null==D&&(D="\u00a0");m.push(b&&b.style?'<pre class="'+
b.style+'">':"<pre>",D);for(b=1;b<a.height;++b)m.push("<br/>&#160;");m.push("</pre>")}++d});ca.style.display="none";Za.innerHTML=m.join("");for(var a=String(t.size).length,b=Za.firstChild,f=b.textContent||b.innerText||b.nodeValue||"",k="";f.length+k.length<a;)k+="\u00a0";k&&b.insertBefore(Ia.createTextNode(k),b.firstChild);ca.style.display="";I.style.marginLeft=ca.offsetWidth+"px";pa=!1}}function Sb(){var a=l.inverted?l.from:l.to;wa();var a=Wa(a,!0),b=R(Q),m=R(ja);$a.style.top=a.y+m.top-b.top+"px";
$a.style.left=a.x+m.left-b.left+"px";q(l.from,l.to)?(sa.style.top=a.y+"px",sa.style.left=(p.lineWrapping?Math.min(a.x,I.offsetWidth):a.x)+"px",sa.style.display=""):sa.style.display="none"}function Tb(a){la=a?la||(l.inverted?l.to:l.from):null}function Da(a,b){var m=la&&V(la);m&&(ha(m,a)?a=m:ha(b,m)&&(b=m));Ua(a,b);gb=!0}function Ua(a,b,m,d){hb=null;null==m&&(m=l.from.line,d=l.to.line);if(!q(l.from,a)||!q(l.to,b)){if(ha(b,a)){var f=b;b=a;a=f}a.line!=m&&(a=ib(a,m,l.from.ch));b.line!=d&&(b=ib(b,d,l.to.ch));
q(a,b)?l.inverted=!1:q(a,l.to)?l.inverted=!1:q(b,l.from)&&(l.inverted=!0);q(a,b)?q(l.from,l.to)||Y.push({from:m,to:d+1}):q(l.from,l.to)?Y.push({from:a.line,to:b.line+1}):(q(a,l.from)||(a.line<m?Y.push({from:a.line,to:Math.min(b.line,m)+1}):Y.push({from:m,to:Math.min(d,a.line)+1})),q(b,l.to)||(b.line<d?Y.push({from:Math.max(m,a.line),to:d+1}):Y.push({from:Math.max(a.line,d),to:b.line+1})));l.from=a;l.to=b;Ea=!0}}function ib(a,b,d){function k(b){for(var s=a.line+b,e=1==b?t.size:-1;s!=e;){var c=f(s);
if(!c.hidden){b=a.ch;if(b>d||b>c.text.length)b=c.text.length;return{line:s,ch:b}}s+=b}}return f(a.line).hidden?a.line>=b?k(1)||k(-1):k(-1)||k(1):a}function Fa(a,b,d){a=V({line:a,ch:b||0});(d?Da:Ua)(a,a)}function jb(a){return Math.max(0,Math.min(a,t.size-1))}function V(a){if(0>a.line)return{line:0,ch:0};if(a.line>=t.size)return{line:t.size-1,ch:f(t.size-1).text.length};var b=a.ch,d=f(a.line).text.length;return null==b||b>d?{line:a.line,ch:d}:0>b?{line:a.line,ch:0}:a}function Ab(a,b){function d(b){if(c==
(0>a?0:n.text.length)){if(b=!b)a:{b=e+a;for(var m=0>a?-1:t.size;b!=m;b+=a){var s=f(b);if(!s.hidden){e=b;n=s;b=!0;break a}}b=void 0}if(b)c=0>a?n.text.length:0;else return!1}else c+=a;return!0}var k=l.inverted?l.from:l.to,e=k.line,c=k.ch,n=f(e);if("char"==b)d();else if("column"==b)d(!0);else if("word"==b)for(k=!1;!(0>a)||d();){if(Na(n.text.charAt(c)))k=!0;else if(k){0>a&&(a=1,d());break}if(0<a&&!d())break}return{line:e,ch:c}}function Ub(a){for(var b=f(a.line).text,d=a.ch,k=a.ch;0<d&&Na(b.charAt(d-1));)--d;
for(;k<b.length&&Na(b.charAt(k));)++k;Da({line:a.line,ch:d},{line:a.line,ch:k})}function pc(a){Da({line:a,ch:0},{line:a,ch:f(a).text.length})}function kb(a,b){b||(b="add");if("smart"==b)if(S.indent)var d=lb(a);else b="prev";var k=f(a),e=k.indentation(p.tabSize),c=k.text.match(/^\s*/)[0],n;"prev"==b?n=a?f(a-1).indentation(p.tabSize):0:"smart"==b?n=S.indent(d,k.text.slice(c.length),k.text):"add"==b?n=e+p.indentUnit:"subtract"==b&&(n=e-p.indentUnit);n=Math.max(0,n);if(n-e){e="";d=0;if(p.indentWithTabs)for(k=
Math.floor(n/p.tabSize);k;--k)d+=p.tabSize,e+="\t";for(;d<n;)++d,e+=" "}else{if(l.from.line!=a&&l.to.line!=a)return;e=c}ra(e,{line:a,ch:0},{line:a,ch:c.length})}function Vb(){S=r.getMode(p,p.mode);t.iter(0,t.size,function(a){a.stateAfter=null});qa=[0];sb()}function qc(){var a=p.gutter||p.lineNumbers;ca.style.display=a?"":"none";a?pa=!0:ja.parentNode.style.marginLeft=0}function rc(a,b){if(p.lineWrapping){Q.className+=" CodeMirror-wrap";var d=y.clientWidth/rb()-3;t.iter(0,t.size,function(a){if(!a.hidden){var b=
Math.ceil(a.text.length/d)||1;1!=b&&k(a,b)}});I.style.width=fa.style.width=""}else Q.className=Q.className.replace(" CodeMirror-wrap",""),Aa=null,za="",t.iter(0,t.size,function(a){1==a.height||a.hidden||k(a,1);a.text.length>za.length&&(za=a.text)});Y.push({from:0,to:t.size})}function Wb(){for(var a='<span class="cm-tab">',b=0;b<p.tabSize;++b)a+=" ";return a+"</span>"}function sc(){zb=Wb();Xa(!0)}function Xb(){y.className=y.className.replace(/\s*cm-s-\w+/g,"")+p.theme.replace(/(^|\s)\s*/g," cm-s-")}
function Bb(){this.set=[]}function Cb(a,b,d){function k(a,b,D,d){f(a).addMark(new ba(b,D,d,e.set))}a=V(a);b=V(b);var e=new Bb;if(a.line==b.line)k(a.line,a.ch,b.ch,d);else{k(a.line,a.ch,null,d);for(var c=a.line+1,n=b.line;c<n;++c)k(c,null,null,d);k(b.line,null,b.ch,d)}Y.push({from:a.line,to:b.line+1});return e}function Yb(a,b){var d=a,k=a;"number"==typeof a?k=f(jb(a)):d=ga(a);if(null!=d&&b(k,d))Y.push({from:d,to:d+1});else return null;return k}function Zb(a,b){return Yb(a,function(a,d){if(a.hidden!=
b)return a.hidden=b,k(a,b?0:1),!b||l.from.line!=d&&l.to.line!=d||Ua(ib(l.from,l.from.line,l.from.ch),ib(l.to,l.to.line,l.to.ch)),pa=!0})}function yb(a){Ga.innerHTML="<pre><span>x</span></pre>";Ga.firstChild.firstChild.firstChild.nodeValue=a;return Ga.firstChild.firstChild.offsetWidth||10}function $b(a,b){var d="";p.lineWrapping&&(d=a.text.indexOf(" ",b+2),d=ka(a.text.slice(b+1,0>d?a.text.length:d+(Ca?5:0))));Ga.innerHTML="<pre>"+a.getHTML(null,null,!1,zb,b)+'<span id="CodeMirror-temp-'+ac+'">'+ka(a.text.charAt(b)||
" ")+"</span>"+d+"</pre>";var d=document.getElementById("CodeMirror-temp-"+ac),f=d.offsetTop,k=d.offsetLeft;Ca&&(b&&0==f&&0==k)&&(f=document.createElement("span"),f.innerHTML="x",d.parentNode.insertBefore(f,d.nextSibling),f=f.offsetTop);return{top:f,left:k}}function Wa(a,b){var d,k=wa(),e=k*(L(t,a.line)-(b?Ya:0));if(0==a.ch)d=0;else{var c=$b(f(a.line),a.ch);d=c.left;p.lineWrapping&&(e+=Math.max(0,c.top))}return{x:d,y:e,yBot:e+k}}function Db(a,b){function d(a){a=$b(l,a);if(g){var b=Math.round(a.top/
k);return Math.max(0,a.left+(b-h)*y.clientWidth)}return a.left}0>b&&(b=0);var k=wa(),e=rb(),c=Ya+Math.floor(b/k),n=oa(t,c);if(n>=t.size)return{line:t.size-1,ch:f(t.size-1).text.length};var l=f(n),u=l.text,g=p.lineWrapping,h=g?c-L(t,n):0;if(0>=a&&0==h)return{line:n,ch:0};for(var A=c=0,u=u.length,B,e=Math.min(u,Math.ceil((a+0.9*h*y.clientWidth)/e));;){var J=d(e);if(J<=a&&e<u)e=Math.min(u,Math.ceil(1.2*e));else{B=J;u=e;break}}if(a>B)return{line:n,ch:u};e=Math.floor(0.8*u);J=d(e);J<a&&(c=e,A=J);for(;;){if(1>=
u-c)return{line:n,ch:B-a>a-A?c:u};e=Math.ceil((c+u)/2);J=d(e);J>a?(u=e,B=J):(c=e,A=J)}}function bc(a){a=Wa(a,!0);var b=R(I);return{x:b.left+a.x,y:b.top+a.y,yBot:b.top+a.yBot}}function wa(){if(null==Ja){Ja="<pre>";for(var a=0;49>a;++a)Ja+="x<br/>";Ja+="x</pre>"}a=ja.clientHeight;if(a==cc)return Eb;cc=a;Ga.innerHTML=Ja;Eb=Ga.firstChild.offsetHeight/50||1;Ga.innerHTML="";return Eb}function rb(){if(y.clientWidth==dc)return ec;dc=y.clientWidth;return ec=yb("x")}function Oa(a,b){var d=R(y,!0),f,k;try{f=
a.clientX,k=a.clientY}catch(e){return null}if(!b&&(f-d.left>y.clientWidth||k-d.top>y.clientHeight))return null;d=R(I,!0);return Db(f-d.left,k-d.top)}function fc(a){function b(){var a=e(H.value).join("\n");a!=k&&x(X)(a,"end");$a.style.position="relative";H.style.cssText=f;Ra=!1;ob(!0);db()}var d=Oa(a);if(d&&!window.opera){(q(l.from,l.to)||ha(d,l.from)||!ha(d,l.to))&&x(Fa)(d.line,d.ch);var f=H.style.cssText;$a.style.position="absolute";H.style.cssText="position: fixed; width: 30px; height: 30px; top: "+
(a.clientY-5)+"px; left: "+(a.clientX-5)+"px; z-index: 1000; background: white; border-width: 0; outline: none; overflow: hidden; opacity: .05; filter: alpha(opacity=5);";Ra=!0;var k=H.value=eb();Ha();H.select();if(Pa){K(a);var c=w(window,"mouseup",function(){c();setTimeout(b,20)},!0)}else setTimeout(b,50)}}function Lb(){clearInterval(pb);var a=!0;sa.style.visibility="";pb=setInterval(function(){sa.style.visibility=(a=!a)?"":"hidden"},650)}function gc(a){function b(a,d,f){if(a.text){var D=a.styles;
a=n?0:a.text.length-1;for(var k,e=n?0:D.length-2,m=n?D.length:-2;e!=m;e+=2*u){var c=D[e];if(null!=D[e+1]&&D[e+1]!=A)a+=u*c.length;else for(var s=n?0:c.length-1,l=n?c.length:-1;s!=l;s+=u,a+=u)if(a>=d&&a<f&&B.test(k=c.charAt(s))){var g=Fb[k];if(">"==g.charAt(1)==n)J.push(k);else{if(J.pop()!=g.charAt(0))return{pos:a,match:!1};if(!J.length)return{pos:a,match:!0}}}}}}var d=l.inverted?l.from:l.to,k=f(d.line),e=d.ch-1,c=0<=e&&Fb[k.text.charAt(e)]||Fb[k.text.charAt(++e)];if(c){c.charAt(0);for(var n=">"==
c.charAt(1),u=n?1:-1,g=k.styles,h=e+1,c=0,p=g.length;c<p;c+=2)if(0>=(h-=g[c].length)){var A=g[c+1];break}for(var J=[k.text.charAt(e)],B=/[(){}[\]]/,c=d.line,p=n?Math.min(c+100,t.size):Math.max(-1,c-100);c!=p;c+=u){var k=f(c),q=c==d.line;if(q=b(k,q&&n?e+1:0,q&&!n?e:k.text.length))break}q||(q={pos:null,match:!1});var A=q.match?"CodeMirror-matchingbracket":"CodeMirror-nonmatchingbracket",N=Cb({line:d.line,ch:e},{line:d.line,ch:e+1},A),R=null!=q.pos&&Cb({line:c,ch:q.pos},{line:c,ch:q.pos+1},A),d=x(function(){N.clear();
R&&R.clear()});a?setTimeout(d,800):mb=d}}function hc(a){var b,d,k=a;for(a-=40;k>a;--k){if(0==k)return 0;var e=f(k-1);if(e.stateAfter)return k;e=e.indentation(p.tabSize);if(null==d||b>e)d=k-1,b=e}return d}function lb(a){var b=hc(a),d=b&&f(b-1).stateAfter,d=d?E(S,d):C(S);t.iter(b,a,function(a){a.highlight(S,d,p.tabSize);a.stateAfter=E(S,d)});b<a&&Y.push({from:b,to:a});a<t.size&&!f(a).stateAfter&&qa.push(a);return d}function lc(a,b){var d=lb(a);t.iter(a,b,function(a){a.highlight(S,d,p.tabSize);a.stateAfter=
E(S,d)})}function tc(){for(var a=+new Date+p.workTime,b=qa.length;qa.length;){var d=f(Z).stateAfter?qa.pop():Z;if(!(d>=t.size)){var k=hc(d),e=k&&f(k-1).stateAfter,e=e?E(S,e):C(S),c=0,n=S.compareStates,l=!1,u=k,g=!1;t.iter(u,t.size,function(b){var f=b.stateAfter;if(+new Date>a)return qa.push(u),sb(p.workDelay),l&&Y.push({from:d,to:u+1}),g=!0;var k=b.highlight(S,e,p.tabSize);k&&(l=!0);b.stateAfter=E(S,e);if(n){if(f&&n(f,e))return!0}else if(!1!==k||!f)c=0;else if(3<++c&&(!S.indent||S.indent(f,"")==S.indent(e,
"")))return!0;++u});if(g)return;l&&Y.push({from:d,to:u+1})}}if(b&&p.onHighlightComplete)p.onHighlightComplete(P)}function sb(a){qa.length&&uc.set(a,x(tc))}function vb(){ya=gb=Ta=null;Y=[];Ea=!1;Sa=[]}function wb(){var a=!1,b;Ea&&(a=!Nb());Y.length?b=Xa(Y,!0):(Ea&&Sb(),pa&&Rb());a&&Nb();Ea&&(mc(),Lb());ma&&(!Ra&&(!0===ya||!1!==ya&&Ea))&&ob(gb);Ea&&p.matchBrackets&&setTimeout(x(function(){mb&&(mb(),mb=null);q(l.from,l.to)&&gc(!1)}),20);var d=Ta,a=Sa;if(Ea&&p.onCursorActivity)p.onCursorActivity(P);if(d&&
p.onChange&&P)p.onChange(P,d);for(d=0;d<a.length;++d)a[d](P);if(b&&p.onUpdate)p.onUpdate(P)}function x(a){return function(){ic++||vb();try{var b=a.apply(this,arguments)}finally{--ic||wb()}return b}}var p={},Gb=r.defaults,ab;for(ab in Gb)Gb.hasOwnProperty(ab)&&(p[ab]=(b&&b.hasOwnProperty(ab)?b:Gb)[ab]);var Ia=p.document,Q=Ia.createElement("div");Q.className="CodeMirror"+(p.lineWrapping?" CodeMirror-wrap":"");Q.innerHTML='<div style="overflow: hidden; position: relative; width: 3px; height: 0px;"><textarea style="position: absolute; padding: 0; width: 1px;" wrap="off" autocorrect="off" autocapitalize="off"></textarea></div><div class="CodeMirror-scroll" tabindex="-1"><div style="position: relative"><div style="position: relative"><div class="CodeMirror-gutter"><div class="CodeMirror-gutter-text"></div></div><div class="CodeMirror-lines"><div style="position: relative"><div style="position: absolute; width: 100%; height: 0; overflow: hidden; visibility: hidden"></div><pre class="CodeMirror-cursor">&#160;</pre><div></div></div></div></div></div></div>';
a.appendChild?a.appendChild(Q):a(Q);var $a=Q.firstChild,H=$a.firstChild,y=Q.lastChild,fa=y.firstChild,fb=fa.firstChild,ca=fb.firstChild,Za=ca.firstChild,I=ca.nextSibling.firstChild,Ga=I.firstChild,sa=Ga.nextSibling,ja=sa.nextSibling;Xb();/AppleWebKit/.test(navigator.userAgent)&&/Mobile\/\w+/.test(navigator.userAgent)&&(H.style.width="0px");F||(I.draggable=!0);null!=p.tabindex&&(H.tabIndex=p.tabindex);p.gutter||p.lineNumbers||(ca.style.display="none");try{yb("x")}catch(Hb){throw Hb.message.match(/runtime/i)&&
(Hb=Error("A CodeMirror inside a P-style element does not work in Internet Explorer. (innerHTML bug)")),Hb;}var ub=new A,uc=new A,pb,S,t=new g([new c([new z("")])]),qa,ma;Vb();var l={from:{line:0,ch:0},to:{line:0,ch:0},inverted:!1},la,nb,bb,Ib,xb=!1,ya,gb,Y,Ta,Ea,Ra,pa,Sa,Ya=0,Z=0,ia=0,Qb=0,mb,za="",Aa,zb=Wb();x(function(){n(p.value||"");ya=!1})();var na=new G;w(y,"mousedown",x(function(a){function b(a){var d=Oa(a,!0);if(d&&!q(d,k)){ma||h();k=d;Da(f,d);ya=!1;var D=Pb();if(d.line>=D.to||d.line<D.from)e=
setTimeout(x(function(){b(a)}),150)}}Tb(a.shiftKey);for(var d=a.target||a.srcElement;d!=Q;d=d.parentNode)if(d.parentNode==fa&&d!=fb)return;for(d=a.target||a.srcElement;d!=Q;d=d.parentNode)if(d.parentNode==Za){if(p.onGutterClick)p.onGutterClick(P,ta(Za.childNodes,d)+Z,a);return v(a)}var f=Oa(a);switch(T(a)){case 3:Pa&&!Ka&&fc(a);return;case 2:f&&Fa(f.line,f.ch,!0);return}if(f){ma||h();d=+new Date;if(bb&&bb.time>d-400&&q(bb.pos,f))return v(a),setTimeout(Ha,20),pc(f.line);if(nb&&nb.time>d-400&&q(nb.pos,
f))return bb={time:d,pos:f},v(a),Ub(f);nb={time:d,pos:f};var k=f,e;if(!xa||q(l.from,l.to)||ha(f,l.from)||ha(l.to,f)){v(a);Fa(f.line,f.ch,!0);var c=w(Ia,"mousemove",x(function(a){clearTimeout(e);v(a);b(a)}),!0),n=w(Ia,"mouseup",x(function(a){clearTimeout(e);var b=Oa(a);b&&Da(f,b);v(a);Ha();ya=!0;c();n()}),!0)}else{F&&(I.draggable=!0);var n=w(Ia,"mouseup",x(function(b){F&&(I.draggable=!1);Ib=!1;n();10>Math.abs(a.clientX-b.clientX)+Math.abs(a.clientY-b.clientY)&&(v(b),Fa(f.line,f.ch,!0),Ha())}),!0);
Ib=!0}}else(a.target||a.srcElement)==y&&v(a)}));w(y,"dblclick",x(function(a){for(var b=a.target||a.srcElement;b!=Q;b=b.parentNode)if(b.parentNode==Za)return v(a);if(b=Oa(a))bb={time:+new Date,pos:b},v(a),Ub(b)}));w(I,"dragstart",function(a){var b=eb();ka(b);a.dataTransfer.setDragImage(ua,0,0);a.dataTransfer.setData("Text",b)});w(I,"selectstart",v);Pa||w(y,"contextmenu",fc);w(y,"scroll",function(){Xa([]);p.fixedGutter&&(ca.style.left=y.scrollLeft+"px");if(p.onScroll)p.onScroll(P)});w(window,"resize",
function(){Xa(!0)});w(H,"keyup",x(function(a){p.onKeyEvent&&p.onKeyEvent(P,$(a))||16==a.keyCode&&(la=null)}));w(H,"input",Va);w(H,"keydown",x(function(a){ma||h();var b=a.keyCode;Ca&&27==b&&(a.returnValue=!1);Tb(16==b||a.shiftKey);p.onKeyEvent&&p.onKeyEvent(P,$(a))||(b=u(a),window.opera&&(Jb=b?a.keyCode:null,!b&&((Ka?a.metaKey:a.ctrlKey)&&88==a.keyCode)&&X("")))}));w(H,"keypress",x(function(a){window.opera&&a.keyCode==Jb?(Jb=null,v(a)):p.onKeyEvent&&p.onKeyEvent(P,$(a))||window.opera&&!a.which&&u(a)||
(p.electricChars&&S.electricChars&&(a=String.fromCharCode(null==a.charCode?a.keyCode:a.charCode),-1<S.electricChars.indexOf(a)&&setTimeout(x(function(){kb(l.to.line,"smart")}),75)),Va())}));w(H,"focus",h);w(H,"blur",N);w(y,"dragenter",K);w(y,"dragover",K);w(y,"drop",x(function(a){a.preventDefault();var b=Oa(a,!0),d=a.dataTransfer.files;if(b&&!p.readOnly)if(d&&d.length&&window.FileReader&&window.File){a=function(a,d){var c=new FileReader;c.onload=function(){k[d]=c.result;++e==f&&(b=V(b),x(function(){var a=
ra(k.join(""),b,b);Da(b,a)})())};c.readAsText(a)};for(var f=d.length,k=Array(f),e=0,c=0;c<f;++c)a(d[c],c)}else try{if(k=a.dataTransfer.getData("Text")){var c=ra(k,b,b),n=l.from,u=l.to;Da(b,c);Ib&&ra("",n,u);Ha()}}catch(g){}}));w(y,"paste",function(){Ha();Va()});w(H,"paste",Va);w(H,"cut",x(function(){X("")}));var jc;try{jc=Ia.activeElement==H}catch(vc){}jc?setTimeout(h,20):N();var P=Q.CodeMirror={getValue:function(a){var b=[];t.iter(0,t.size,function(a){b.push(a.text)});return b.join("\n")},setValue:x(n),
getSelection:eb,replaceSelection:x(X),focus:function(){Ha();h();Va()},setOption:function(a,b){var d=p[a];p[a]=b;"mode"==a||"indentUnit"==a?Vb():"readOnly"==a&&b?(N(),H.blur()):"theme"==a?Xb():"lineWrapping"==a&&d!=b?x(rc)():"tabSize"==a&&x(sc)();"lineNumbers"!=a&&"gutter"!=a&&"firstLineNumber"!=a&&"theme"!=a||x(qc)()},getOption:function(a){return p[a]},undo:x(function(){M(na.done,na.undone)}),redo:x(function(){M(na.undone,na.done)}),indentLine:x(function(a,b){d(a)&&kb(a,null==b?"smart":b?"add":"subtract")}),
indentSelection:x(function(a){if(q(l.from,l.to))return kb(l.from.line,a);for(var b=l.to.line-(l.to.ch?0:1),d=l.from.line;d<=b;++d)kb(d,a)}),historySize:function(){return{undo:na.done.length,redo:na.undone.length}},clearHistory:function(){na=new G},matchBrackets:x(function(){gc(!0)}),getTokenAt:x(function(a){a=V(a);return f(a.line).getTokenAt(S,lb(a.line),a.ch)}),getStateAfter:function(a){a=jb(null==a?t.size-1:a);return lb(a+1)},cursorCoords:function(a){null==a&&(a=l.inverted);return bc(a?l.from:l.to)},
charCoords:function(a){return bc(V(a))},coordsChar:function(a){var b=R(I);return Db(a.x-b.left,a.y-b.top)},markText:x(Cb),setBookmark:function(a){a=V(a);var b=new W(a.ch);f(a.line).addMark(b);return b},setMarker:x(function(a,b,d){"number"==typeof a&&(a=f(jb(a)));a.gutterMarker={text:b,style:d};pa=!0;return a}),clearMarker:x(function(a){"number"==typeof a&&(a=f(jb(a)));a.gutterMarker=null;pa=!0}),setLineClass:x(function(a,b){return Yb(a,function(a){if(a.className!=b)return a.className=b,!0})}),hideLine:x(function(a){return Zb(a,
!0)}),showLine:x(function(a){return Zb(a,!1)}),onDeleteLine:function(a,b){if("number"==typeof a){if(!d(a))return null;a=f(a)}(a.handlers||(a.handlers=[])).push(b);return a},lineInfo:function(a){if("number"==typeof a){if(!d(a))return null;var b=a;a=f(a);if(!a)return null}else if(b=ga(a),null==b)return null;var k=a.gutterMarker;return{line:b,handle:a,text:a.text,markerText:k&&k.text,markerClass:k&&k.style,lineClass:a.className}},addWidget:function(a,b,d,f,k){a=Wa(V(a));var e=a.yBot,c=a.x;b.style.position=
"absolute";fa.appendChild(b);if("over"==f)e=a.y;else if("near"==f){f=Math.max(y.offsetHeight,t.height*wa());var n=Math.max(fa.clientWidth,I.clientWidth)-I.offsetLeft;a.yBot+b.offsetHeight>f&&a.y>b.offsetHeight&&(e=a.y-b.offsetHeight);c+b.offsetWidth>n&&(c=n-b.offsetWidth)}b.style.top=e+I.offsetTop+"px";b.style.left=b.style.right="";"right"==k?(c=fa.clientWidth-b.offsetWidth,b.style.right="0px"):("left"==k?c=0:"middle"==k&&(c=(fa.clientWidth-b.offsetWidth)/2),b.style.left=c+I.offsetLeft+"px");d&&Ob(c,
e,c+b.offsetWidth,e+b.offsetHeight)},lineCount:function(){return t.size},clipPos:V,getCursor:function(a){null==a&&(a=l.inverted);return{line:(a?l.from:l.to).line,ch:(a?l.from:l.to).ch}},somethingSelected:function(){return!q(l.from,l.to)},setCursor:x(function(a,b,d){null==b&&"number"==typeof a.line?Fa(a.line,a.ch,d):Fa(a,b,d)}),setSelection:x(function(a,b,d){(d?Da:Ua)(V(a),V(b||a))}),getLine:function(a){if(d(a))return f(a).text},getLineHandle:function(a){if(d(a))return f(a)},setLine:x(function(a,b){d(a)&&
ra(b,{line:a,ch:0},{line:a,ch:f(a).text.length})}),removeLine:x(function(a){d(a)&&ra("",{line:a,ch:0},V({line:a+1,ch:0}))}),replaceRange:x(ra),getRange:function(a,b){return da(V(a),V(b))},execCommand:function(a){return Ma[a](P)},moveH:x(function(a,b){var d=0>a?l.from:l.to;if(la||q(l.from,l.to))d=Ab(a,b);Fa(d.line,d.ch,!0)}),deleteH:x(function(a,b){q(l.from,l.to)?0>a?ra("",Ab(a,b),l.to):ra("",l.from,Ab(a,b)):ra("",l.from,l.to);gb=!0}),moveV:x(function(a,b){var d=0,f=Wa(l.inverted?l.from:l.to,!0);null!=
hb&&(f.x=hb);"page"==b?d=y.clientHeight:"line"==b&&(d=wa());d=Db(f.x,f.y+d*a+2);Fa(d.line,d.ch,!0);hb=f.x}),toggleOverwrite:function(){xb=!xb},posFromIndex:function(a){var b=0,d;t.iter(0,t.size,function(f){f=f.text.length+1;if(f>a)return d=a,!0;a-=f;++b});return V({line:b,ch:d})},indexFromPos:function(a){if(0>a.line||0>a.ch)return 0;var b=a.ch;t.iter(0,a.line,function(a){b+=a.text.length+1});return b},operation:function(a){return x(a)()},refresh:function(){Xa(!0)},getInputField:function(){return H},
getWrapperElement:function(){return Q},getScrollerElement:function(){return y},getGutterElement:function(){return ca}},Jb=null,tb=!1,Ba="",hb=null;Bb.prototype.clear=x(function(){for(var a=Infinity,b=-Infinity,d=0,f=this.set.length;d<f;++d){var k=this.set[d],e=k.marked;if(e&&k.parent)for(k=ga(k),a=Math.min(a,k),b=Math.max(b,k),k=0;k<e.length;++k)e[k].set==this.set&&e.splice(k--,1)}Infinity!=a&&Y.push({from:a,to:b+1})});Bb.prototype.find=function(){for(var a,b,d=0,f=this.set.length;d<f;++d)for(var k=
this.set[d],e=k.marked,c=0;c<e.length;++c){var n=e[c];if(n.set==this.set&&(null!=n.from||null!=n.to)){var l=ga(k);null!=l&&(null!=n.from&&(a={line:l,ch:n.from}),null!=n.to&&(b={line:l,ch:n.to}))}}return{from:a,to:b}};var ac=Math.floor(16777215*Math.random()).toString(16),Eb,cc,Ja,ec,dc=0,Fb={"(":")>",")":"(<","[":"]>","]":"[<","{":"}>","}":"{<"},ic=0,cb;for(cb in Qa)Qa.propertyIsEnumerable(cb)&&!P.propertyIsEnumerable(cb)&&(P[cb]=Qa[cb]);return P}function O(a,b,d){function f(a,b,d){var e=b[a];if(null!=
e)return e;null==d&&(d=b.fallthrough);if(null==d)return b.catchall;if("string"==typeof d)return f(a,aa[d]);b=0;for(var c=d.length;b<c;++b)if(e=f(a,aa[d[b]]),null!=e)return e;return null}return b?f(a,b,d):f(a,aa[d])}function E(a,b){if(!0===b)return b;if(a.copyState)return a.copyState(b);var d={},f;for(f in b){var k=b[f];k instanceof Array&&(k=k.concat([]));d[f]=k}return d}function C(a,b,d){return a.startState?a.startState(b,d):!0}function U(a,b){this.pos=this.start=0;this.string=a;this.tabSize=b||
8}function ba(a,b,d,f){this.from=a;this.to=b;this.style=d;this.set=f}function W(a){this.to=this.from=a;this.line=null}function z(a,b){this.styles=b||[a,null];this.text=a;this.height=1;this.stateAfter=this.parent=this.hidden=this.marked=this.gutterMarker=this.className=this.handlers=null}function h(a,b,d,f){for(var k=0,e=0,c=0;e<b;k+=2){var g=d[k],h=e+g.length;0==c?(h>a&&f.push(g.slice(a-e,Math.min(g.length,b-e)),d[k+1]),h>=a&&(c=1)):1==c&&(h>b?f.push(g.slice(0,b-e),d[k+1]):f.push(g,d[k+1]));e=h}}
function c(a){this.lines=a;this.parent=null;for(var b=0,d=a.length,f=0;b<d;++b)a[b].parent=this,f+=a[b].height;this.height=f}function g(a){this.children=a;for(var b=0,d=0,f=0,k=a.length;f<k;++f){var e=a[f],b=b+e.chunkSize(),d=d+e.height;e.parent=this}this.size=b;this.height=d;this.parent=null}function ga(a){if(null==a.parent)return null;var b=a.parent;a=ta(b.lines,a);for(var d=b.parent;d;b=d,d=d.parent)for(var f=0;d.children[f]!=b;++f)a+=d.children[f].chunkSize();return a}function oa(a,b){var d=0;
a:do{for(var f=0,k=a.children.length;f<k;++f){var e=a.children[f],c=e.height;if(b<c){a=e;continue a}b-=c;d+=e.chunkSize()}return d}while(!a.lines);f=0;for(k=a.lines.length;f<k;++f){e=a.lines[f].height;if(b<e)break;b-=e}return d+f}function L(a,b){var d=0;a:do{for(var f=0,k=a.children.length;f<k;++f){var e=a.children[f],c=e.chunkSize();if(b<c){a=e;continue a}b-=c;d+=e.height}return d}while(!a.lines);for(f=0;f<b;++f)d+=a.lines[f].height;return d}function G(){this.time=0;this.done=[];this.undone=[]}function M(){K(this)}
function $(a){a.stop||(a.stop=M);return a}function v(a){a.preventDefault?a.preventDefault():a.returnValue=!1}function da(a){a.stopPropagation?a.stopPropagation():a.cancelBubble=!0}function K(a){v(a);da(a)}function T(a){if(a.which)return a.which;if(a.button&1)return 1;if(a.button&2)return 3;if(a.button&4)return 2}function w(a,b,d,f){if("function"==typeof a.addEventListener){if(a.addEventListener(b,d,!1),f)return function(){a.removeEventListener(b,d,!1)}}else{var k=function(a){d(a||window.event)};a.attachEvent("on"+
b,k);if(f)return function(){a.detachEvent("on"+b,k)}}}function A(){this.id=null}function N(a,b,d){null==b&&(b=a.search(/[^\s\u00a0]/),-1==b&&(b=a.length));for(var f=0,k=0;f<b;++f)"\t"==a.charAt(f)?k+=d-k%d:++k;return k}function R(a,b){for(var d=a.ownerDocument.body,f=0,k=0,e=!1,c=a;c;c=c.offsetParent){var g=c.offsetLeft,h=c.offsetTop;c==d?(f+=Math.abs(g),k+=Math.abs(h)):(f+=g,k+=h);if(g=b)g=c.currentStyle?c.currentStyle:window.getComputedStyle(c,null),g="fixed"==g.position;g&&(e=!0)}d=b&&!e?null:
d;for(c=a.parentNode;c!=d;c=c.parentNode)null!=c.scrollLeft&&(f-=c.scrollLeft,k-=c.scrollTop);return{left:f,top:k}}function q(a,b){return a.line==b.line&&a.ch==b.ch}function ha(a,b){return a.line<b.line||a.line==b.line&&a.ch<b.ch}function ka(a){ua.textContent=a;return ua.innerHTML}function qb(a,b){if(!b)return a?a.length:0;if(!a)return b.length;for(var d=a.length,f=b.length;0<=d&&0<=f&&a.charAt(d)==b.charAt(f);--d,--f);return f+1}function ta(a,b){if(a.indexOf)return a.indexOf(b);for(var d=0,f=a.length;d<
f;++d)if(a[d]==b)return d;return-1}function Na(a){return/\w/.test(a)||a.toUpperCase()!=a.toLowerCase()}r.defaults={value:"",mode:null,theme:"default",indentUnit:2,indentWithTabs:!1,tabSize:4,keyMap:"default",extraKeys:null,electricChars:!0,onKeyEvent:null,lineWrapping:!1,lineNumbers:!1,gutter:!1,fixedGutter:!1,firstLineNumber:1,readOnly:!1,onChange:null,onCursorActivity:null,onGutterClick:null,onHighlightComplete:null,onUpdate:null,onFocus:null,onBlur:null,onScroll:null,matchBrackets:!1,workTime:100,
workDelay:200,pollInterval:100,undoDepth:40,tabindex:null,document:window.document};var Ka=/Mac/.test(navigator.platform);/Win/.test(navigator.platform);var va={},X={};r.defineMode=function(a,b){r.defaults.mode||"null"==a||(r.defaults.mode=a);va[a]=b};r.defineMIME=function(a,b){X[a]=b};r.getMode=function(a,b){"string"==typeof b&&X.hasOwnProperty(b)&&(b=X[b]);if("string"==typeof b)var d=b,f={};else null!=b&&(d=b.name,f=b);var k=va[d];return k?k(a,f||{}):(window.console&&console.warn("No mode "+d+" found, falling back to plain text."),
r.getMode(a,"text/plain"))};r.listModes=function(){var a=[],b;for(b in va)va.propertyIsEnumerable(b)&&a.push(b);return a};r.listMIMEs=function(){var a=[],b;for(b in X)X.propertyIsEnumerable(b)&&a.push({mime:b,mode:X[b]});return a};var Qa=r.extensions={};r.defineExtension=function(a,b){Qa[a]=b};var Ma=r.commands={selectAll:function(a){a.setSelection({line:0,ch:0},{line:a.lineCount()-1})},killLine:function(a){var b=a.getCursor(!0),d=a.getCursor(!1),f=!q(b,d);f||a.getLine(b.line).length!=b.ch?a.replaceRange("",
b,f?d:{line:b.line}):a.replaceRange("",b,{line:b.line+1,ch:0})},deleteLine:function(a){var b=a.getCursor().line;a.replaceRange("",{line:b,ch:0},{line:b})},undo:function(a){a.undo()},redo:function(a){a.redo()},goDocStart:function(a){a.setCursor(0,0,!0)},goDocEnd:function(a){a.setSelection({line:a.lineCount()-1},null,!0)},goLineStart:function(a){a.setCursor(a.getCursor().line,0,!0)},goLineStartSmart:function(a){var b=a.getCursor(),d=a.getLine(b.line),d=Math.max(0,d.search(/\S/));a.setCursor(b.line,
b.ch<=d&&b.ch?0:d,!0)},goLineEnd:function(a){a.setSelection({line:a.getCursor().line},null,!0)},goLineUp:function(a){a.moveV(-1,"line")},goLineDown:function(a){a.moveV(1,"line")},goPageUp:function(a){a.moveV(-1,"page")},goPageDown:function(a){a.moveV(1,"page")},goCharLeft:function(a){a.moveH(-1,"char")},goCharRight:function(a){a.moveH(1,"char")},goColumnLeft:function(a){a.moveH(-1,"column")},goColumnRight:function(a){a.moveH(1,"column")},goWordLeft:function(a){a.moveH(-1,"word")},goWordRight:function(a){a.moveH(1,
"word")},delCharLeft:function(a){a.deleteH(-1,"char")},delCharRight:function(a){a.deleteH(1,"char")},delWordLeft:function(a){a.deleteH(-1,"word")},delWordRight:function(a){a.deleteH(1,"word")},indentAuto:function(a){a.indentSelection("smart")},indentMore:function(a){a.indentSelection("add")},indentLess:function(a){a.indentSelection("subtract")},insertTab:function(a){a.replaceSelection("\t","end")},transposeChars:function(a){var b=a.getCursor(),d=a.getLine(b.line);0<b.ch&&b.ch<d.length-1&&a.replaceRange(d.charAt(b.ch)+
d.charAt(b.ch-1),{line:b.line,ch:b.ch-1},{line:b.line,ch:b.ch+1})},newlineAndIndent:function(a){a.replaceSelection("\n","end");a.indentLine(a.getCursor().line)},toggleOverwrite:function(a){a.toggleOverwrite()}},aa=r.keyMap={};aa.basic={Left:"goCharLeft",Right:"goCharRight",Up:"goLineUp",Down:"goLineDown",End:"goLineEnd",Home:"goLineStartSmart",PageUp:"goPageUp",PageDown:"goPageDown",Delete:"delCharRight",Backspace:"delCharLeft",Tab:"indentMore","Shift-Tab":"indentLess",Enter:"newlineAndIndent",Insert:"toggleOverwrite"};
aa.pcDefault={"Ctrl-A":"selectAll","Ctrl-D":"deleteLine","Ctrl-Z":"undo","Shift-Ctrl-Z":"redo","Ctrl-Y":"redo","Ctrl-Home":"goDocStart","Alt-Up":"goDocStart","Ctrl-End":"goDocEnd","Ctrl-Down":"goDocEnd","Ctrl-Left":"goWordLeft","Ctrl-Right":"goWordRight","Alt-Left":"goLineStart","Alt-Right":"goLineEnd","Ctrl-Backspace":"delWordLeft","Ctrl-Delete":"delWordRight","Ctrl-S":"save","Ctrl-F":"find","Ctrl-G":"findNext","Shift-Ctrl-G":"findPrev","Shift-Ctrl-F":"replace","Shift-Ctrl-R":"replaceAll",fallthrough:"basic"};
aa.macDefault={"Cmd-A":"selectAll","Cmd-D":"deleteLine","Cmd-Z":"undo","Shift-Cmd-Z":"redo","Cmd-Y":"redo","Cmd-Up":"goDocStart","Cmd-End":"goDocEnd","Cmd-Down":"goDocEnd","Alt-Left":"goWordLeft","Alt-Right":"goWordRight","Cmd-Left":"goLineStart","Cmd-Right":"goLineEnd","Alt-Backspace":"delWordLeft","Ctrl-Alt-Backspace":"delWordRight","Alt-Delete":"delWordRight","Cmd-S":"save","Cmd-F":"find","Cmd-G":"findNext","Shift-Cmd-G":"findPrev","Cmd-Alt-F":"replace","Shift-Cmd-Alt-F":"replaceAll",fallthrough:["basic",
"emacsy"]};aa["default"]=Ka?aa.macDefault:aa.pcDefault;aa.emacsy={"Ctrl-F":"goCharRight","Ctrl-B":"goCharLeft","Ctrl-P":"goLineUp","Ctrl-N":"goLineDown","Alt-F":"goWordRight","Alt-B":"goWordLeft","Ctrl-A":"goLineStart","Ctrl-E":"goLineEnd","Ctrl-V":"goPageUp","Shift-Ctrl-V":"goPageDown","Ctrl-D":"delCharRight","Ctrl-H":"delCharLeft","Alt-D":"delWordRight","Alt-Backspace":"delWordLeft","Ctrl-K":"killLine","Ctrl-T":"transposeChars"};r.fromTextArea=function(a,b){function d(){a.value=c.getValue()}b||
(b={});b.value=a.value;!b.tabindex&&a.tabindex&&(b.tabindex=a.tabindex);if(a.form){var f=w(a.form,"submit",d,!0);if("function"==typeof a.form.submit){var k=a.form.submit,e=function(){d();a.form.submit=k;a.form.submit();a.form.submit=e};a.form.submit=e}}a.style.display="none";var c=r(function(b){a.parentNode.insertBefore(b,a.nextSibling)},b);c.save=d;c.getTextArea=function(){return a};c.toTextArea=function(){d();a.parentNode.removeChild(c.getWrapperElement());a.style.display="";a.form&&(f(),"function"==
typeof a.form.submit&&(a.form.submit=k))};return c};r.copyState=E;r.startState=C;U.prototype={eol:function(){return this.pos>=this.string.length},sol:function(){return 0==this.pos},peek:function(){return this.string.charAt(this.pos)},next:function(){if(this.pos<this.string.length)return this.string.charAt(this.pos++)},eat:function(a){var b=this.string.charAt(this.pos);if("string"==typeof a?b==a:b&&(a.test?a.test(b):a(b)))return++this.pos,b},eatWhile:function(a){for(var b=this.pos;this.eat(a););return this.pos>
b},eatSpace:function(){for(var a=this.pos;/[\s\u00a0]/.test(this.string.charAt(this.pos));)++this.pos;return this.pos>a},skipToEnd:function(){this.pos=this.string.length},skipTo:function(a){a=this.string.indexOf(a,this.pos);if(-1<a)return this.pos=a,!0},backUp:function(a){this.pos-=a},column:function(){return N(this.string,this.start,this.tabSize)},indentation:function(){return N(this.string,null,this.tabSize)},match:function(a,b,d){if("string"==typeof a){if((d?this.string.toLowerCase():this.string).indexOf(d?
a.toLowerCase():a,this.pos)==this.pos)return!1!==b&&(this.pos+=a.length),!0}else return(a=this.string.slice(this.pos).match(a))&&!1!==b&&(this.pos+=a[0].length),a},current:function(){return this.string.slice(this.start,this.pos)}};r.StringStream=U;ba.prototype={attach:function(a){this.set.push(a)},detach:function(a){a=ta(this.set,a);-1<a&&this.set.splice(a,1)},split:function(a,b){return this.to<=a&&null!=this.to?null:new ba(this.from<a||null==this.from?null:this.from-a+b,null==this.to?null:this.to-
a+b,this.style,this.set)},dup:function(){return new ba(null,null,this.style,this.set)},clipTo:function(a,b,d,f,k){null!=this.from&&this.from>=b&&(this.from=Math.max(f,this.from)+k);null!=this.to&&this.to>b&&(this.to=f<this.to?this.to+k:b);a&&(f>this.from&&(f<this.to||null==this.to))&&(this.from=null);d&&((b<this.to||null==this.to)&&(b>this.from||null==this.from))&&(this.to=null)},isDead:function(){return null!=this.from&&null!=this.to&&this.from>=this.to},sameSet:function(a){return this.set==a.set}};
W.prototype={attach:function(a){this.line=a},detach:function(a){this.line==a&&(this.line=null)},split:function(a,b){if(a<this.from)return this.from=this.to=this.from-a+b,this},isDead:function(){return this.from>this.to},clipTo:function(a,b,d,f,k){(a||b<this.from)&&(d||f>this.to)?(this.from=0,this.to=-1):this.from>b&&(this.from=this.to=Math.max(f,this.from)+k)},sameSet:function(a){return!1},find:function(){return this.line&&this.line.parent?{line:ga(this.line),ch:this.from}:null},clear:function(){if(this.line){var a=
ta(this.line.marked,this);-1!=a&&this.line.marked.splice(a,1);this.line=null}}};z.inheritMarks=function(a,b){var d=new z(a),f=b&&b.marked;if(f)for(var k=0;k<f.length;++k)if(null==f[k].to&&f[k].style){var e=d.marked||(d.marked=[]),c=f[k].dup();e.push(c);c.attach(d)}return d};z.prototype={replace:function(a,b,d){var f=[],k=this.marked,e=null==b?this.text.length:b;h(0,a,this.styles,f);d&&f.push(d,null);h(e,this.text.length,this.styles,f);this.styles=f;this.text=this.text.slice(0,a)+d+this.text.slice(e);
this.stateAfter=null;if(k){d=d.length-(e-a);for(var f=0,c=k[f];f<k.length;++f)c.clipTo(null==a,a||0,null==b,e,d),c.isDead()&&(c.detach(this),k.splice(f--,1))}},split:function(a,b){var d=[b,null],f=this.marked;h(a,this.text.length,this.styles,d);d=new z(b+this.text.slice(a),d);if(f)for(var e=0;e<f.length;++e){var c=f[e].split(a,b.length);c&&(d.marked||(d.marked=[]),d.marked.push(c),c.attach(d))}return d},append:function(a){var b=this.text.length,d=a.marked,f=this.marked;this.text+=a.text;h(0,a.text.length,
a.styles,this.styles);if(f)for(a=0;a<f.length;++a)null==f[a].to&&(f[a].to=b);if(d&&d.length)a:for(f||(this.marked=f=[]),a=0;a<d.length;++a){var e=d[a];if(!e.from)for(var c=0;c<f.length;++c){var g=f[c];if(g.to==b&&g.sameSet(e)){g.to=null==e.to?null:e.to+b;g.isDead()&&(g.detach(this),d.splice(a--,1));continue a}}f.push(e);e.attach(this);e.from+=b;null!=e.to&&(e.to+=b)}},fixMarkEnds:function(a){var b=this.marked;a=a.marked;if(b)for(var d=0;d<b.length;++d){var f=b[d],e=null==f.to;if(e&&a)for(var c=0;c<
a.length;++c)if(a[c].sameSet(f)){e=!1;break}e&&(f.to=this.text.length)}},fixMarkStarts:function(){var a=this.marked;if(a)for(var b=0;b<a.length;++b)null==a[b].from&&(a[b].from=0)},addMark:function(a){a.attach(this);null==this.marked&&(this.marked=[]);this.marked.push(a);this.marked.sort(function(a,d){return(a.from||0)-(d.from||0)})},highlight:function(a,b,d){d=new U(this.text,d);var f=this.styles,e=0,c=!1,g=f[0],h;for(""==this.text&&a.blankLine&&a.blankLine(b);!d.eol();){var A=a.token(d,b),J=this.text.slice(d.start,
d.pos);d.start=d.pos;e&&f[e-1]==A?f[e-2]+=J:J&&(!c&&(f[e+1]!=A||e&&f[e-2]!=h)&&(c=!0),f[e++]=J,f[e++]=A,h=g,g=f[e]);if(5E3<d.pos){f[e++]=this.text.slice(d.pos);f[e++]=null;break}}f.length!=e&&(f.length=e,c=!0);e&&f[e-2]!=h&&(c=!0);return c||(5>f.length&&10>this.text.length?null:!1)},getTokenAt:function(a,b,d){for(var e=new U(this.text);e.pos<d&&!e.eol();){e.start=e.pos;var c=a.token(e,b)}return{start:e.start,end:e.pos,string:e.current(),className:c||null,state:b}},indentation:function(a){return N(this.text,
null,a)},getHTML:function(a,b,d,e,c){function g(a,b){a&&(A&&(Ca&&" "==a.charAt(0))&&(a="\u00a0"+a.slice(1)),A=!1,b?h.push('<span class="',b,'">',ka(a).replace(/\t/g,e),"</span>"):h.push(ka(a).replace(/\t/g,e)))}var h=[],A=!0;d&&h.push(this.className?'<pre class="'+this.className+'">':"<pre>");var J=this.styles,B=this.text,q=this.marked;a==b&&(a=null);var N=B.length;null!=c&&(N=Math.min(c,N));if(B||null!=c)if(q||null!=a){c=B=0;var R="",r=-1,v=null,ga=function(){q&&(r+=1,v=r<q.length?q[r]:null)};for(ga();B<
N;){var w=N,z="";if(null!=a)if(a>B)w=a;else if(null==b||b>B)z=" CodeMirror-selected",null!=b&&(w=Math.min(w,b));for(;v&&null!=v.to&&v.to<=B;)ga();v&&(v.from>B?w=Math.min(w,v.from):(z+=" "+v.style,null!=v.to&&(w=Math.min(w,v.to))));for(;;){var E=B+R.length,F=C;z&&(F=C?C+z:z);g(E>w?R.slice(0,w-B):R,F);if(E>=w){R=R.slice(w-B);B=w;break}B=E;R=J[c++];C="cm-"+J[c++]}}null!=a&&null==b&&g(" ","CodeMirror-selected")}else for(a=c=0;a<N;c+=2){b=J[c];var C=J[c+1],B=b.length;a+B>N&&(b=b.slice(0,N-a));a+=B;g(b,
C&&"cm-"+C)}else g(" ",null!=a&&null==b?"CodeMirror-selected":null);d&&h.push("</pre>");return h.join("")},cleanUp:function(){this.parent=null;if(this.marked)for(var a=0,b=this.marked.length;a<b;++a)this.marked[a].detach(this)}};c.prototype={chunkSize:function(){return this.lines.length},remove:function(a,b,d){for(var e=a,c=a+b;e<c;++e){var g=this.lines[e];this.height-=g.height;g.cleanUp();if(g.handlers)for(var h=0;h<g.handlers.length;++h)d.push(g.handlers[h])}this.lines.splice(a,b)},collapse:function(a){a.splice.apply(a,
[a.length,0].concat(this.lines))},insertHeight:function(a,b,d){this.height+=d;this.lines.splice.apply(this.lines,[a,0].concat(b));a=0;for(d=b.length;a<d;++a)b[a].parent=this},iterN:function(a,b,d){for(b=a+b;a<b;++a)if(d(this.lines[a]))return!0}};g.prototype={chunkSize:function(){return this.size},remove:function(a,b,d){this.size-=b;for(var e=0;e<this.children.length;++e){var k=this.children[e],g=k.chunkSize();if(a<g){var h=Math.min(b,g-a),A=k.height;k.remove(a,h,d);this.height-=A-k.height;g==h&&(this.children.splice(e--,
1),k.parent=null);if(0==(b-=h))break;a=0}else a-=g}25>this.size-b&&(a=[],this.collapse(a),this.children=[new c(a)])},collapse:function(a){for(var b=0,d=this.children.length;b<d;++b)this.children[b].collapse(a)},insert:function(a,b){for(var d=0,e=0,c=b.length;e<c;++e)d+=b[e].height;this.insertHeight(a,b,d)},insertHeight:function(a,b,d){this.size+=b.length;this.height+=d;for(var e=0,k=this.children.length;e<k;++e){var g=this.children[e],h=g.chunkSize();if(a<=h){g.insertHeight(a,b,d);if(g.lines&&50<
g.lines.length){for(;50<g.lines.length;)a=g.lines.splice(g.lines.length-25,25),a=new c(a),g.height-=a.height,this.children.splice(e+1,0,a),a.parent=this;this.maybeSpill()}break}a-=h}},maybeSpill:function(){if(!(10>=this.children.length)){var a=this;do{var b=a.children.splice(a.children.length-5,5),b=new g(b);if(a.parent){a.size-=b.size;a.height-=b.height;var d=ta(a.parent.children,a);a.parent.children.splice(d+1,0,b)}else d=new g(a.children),d.parent=a,a.children=[d,b],a=d;b.parent=a.parent}while(10<
a.children.length);a.parent.maybeSpill()}},iter:function(a,b,d){this.iterN(a,b-a,d)},iterN:function(a,b,d){for(var e=0,c=this.children.length;e<c;++e){var g=this.children[e],h=g.chunkSize();if(a<h){h=Math.min(b,h-a);if(g.iterN(a,h,d))return!0;if(0==(b-=h))break;a=0}else a-=h}}};G.prototype={addChange:function(a,b,d){this.undone.length=0;var e=+new Date,c=this.done[this.done.length-1];if(400<e-this.time||!c||c.start>a+b||c.start+c.added<a-c.added+c.old.length)this.done.push({start:a,added:b,old:d});
else{var g=0;if(a<c.start){for(var h=c.start-a-1;0<=h;--h)c.old.unshift(d[h]);c.added+=c.start-a;c.start=a}else c.start<a&&(g=a-c.start,b+=g);h=c.added-g;for(a=d.length;h<a;++h)c.old.push(d[h]);c.added<b&&(c.added=b)}this.time=e}};r.e_stop=K;r.e_preventDefault=v;r.e_stopPropagation=da;r.connect=w;A.prototype={set:function(a,b){clearTimeout(this.id);this.id=setTimeout(b,a)}};var xa=/MSIE [1-8]\b/.test(navigator.userAgent)?!1:"draggable"in document.createElement("div"),Pa=/gecko\/\d{7}/i.test(navigator.userAgent),
Ca=/MSIE \d/.test(navigator.userAgent),F=/WebKit\//.test(navigator.userAgent);(function(){var a=document.createElement("textarea");a.value="foo\nbar";a.value.indexOf("\r")})();null!=document.documentElement.getBoundingClientRect&&(R=function(a,b){try{var d=a.getBoundingClientRect(),d={top:d.top,left:d.left}}catch(e){d={top:0,left:0}}if(!b)if(null==window.pageYOffset){var c=document.documentElement||document.body.parentNode;null==c.scrollTop&&(c=document.body);d.top+=c.scrollTop;d.left+=c.scrollLeft}else d.top+=
window.pageYOffset,d.left+=window.pageXOffset;return d});var ua=document.createElement("pre");"\na"==ka("a")?ka=function(a){ua.textContent=a;return ua.innerHTML.slice(1)}:"\t"!=ka("\t")&&(ka=function(a){ua.innerHTML="";ua.appendChild(document.createTextNode(a));return ua.innerHTML});r.htmlEscape=ka;var e=3!="\n\nb".split(/\n/).length?function(a){for(var b=0,d,e=[];-1<(d=a.indexOf("\n",b));)e.push(a.slice(b,"\r"==a.charAt(d-1)?d-1:d)),b=d+1;e.push(a.slice(b));return e}:function(a){return a.split(/\r?\n/)};
r.splitLines=e;var J=window.getSelection?function(a){try{return a.selectionStart!=a.selectionEnd}catch(b){return!1}}:function(a){try{var b=a.ownerDocument.selection.createRange()}catch(d){}return b&&b.parentElement()==a?0!=b.compareEndPoints("StartToEnd",b):!1};r.defineMode("null",function(){return{token:function(a){a.skipToEnd()}}});r.defineMIME("text/plain","null");var B={3:"Enter",8:"Backspace",9:"Tab",13:"Enter",16:"Shift",17:"Ctrl",18:"Alt",19:"Pause",20:"CapsLock",27:"Esc",32:"Space",33:"PageUp",
34:"PageDown",35:"End",36:"Home",37:"Left",38:"Up",39:"Right",40:"Down",44:"PrintScrn",45:"Insert",46:"Delete",59:";",91:"Mod",92:"Mod",93:"Mod",186:";",187:"=",188:",",189:"-",190:".",191:"/",192:"`",219:"[",220:"\\",221:"]",222:"'",63276:"PageUp",63277:"PageDown",63275:"End",63273:"Home",63234:"Left",63232:"Up",63235:"Right",63233:"Down",63302:"Insert",63272:"Delete"};r.keyNames=B;(function(){for(var a=0;10>a;a++)B[a+48]=String(a);for(a=65;90>=a;a++)B[a]=String.fromCharCode(a);for(a=1;12>=a;a++)B[a+
111]=B[a+63235]="F"+a})();return r}();
CodeMirror.defineMode("xml",function(r,O){function E(c,g){function h(q){g.tokenize=q;return q(c,g)}var q=c.next();if("<"==q){if(c.eat("!"))return c.eat("[")?c.match("CDATA[")?h(ba("atom","]]\x3e")):null:c.match("--")?h(ba("comment","--\x3e")):c.match("DOCTYPE",!0,!0)?(c.eatWhile(/[\w\._\-]/),h(W(1))):null;if(c.eat("?"))return c.eatWhile(/[\w\._\-]/),g.tokenize=ba("meta","?>"),"meta";K=c.eat("/")?"closeTag":"openTag";c.eatSpace();for(da="";q=c.eat(/[^\s\u00a0=<>\"\'\/?]/);)da+=q;g.tokenize=C;return"tag"}if("&"==
q)return c.eatWhile(/[^;]/),c.eat(";"),"atom";c.eatWhile(/[^&<]/);return null}function C(c,g){var h=c.next();if(">"==h||"/"==h&&c.eat(">"))return g.tokenize=E,K=">"==h?"endTag":"selfcloseTag","tag";if("="==h)return K="equals",null;if(/[\'\"]/.test(h))return g.tokenize=U(h),g.tokenize(c,g);c.eatWhile(/[^\s\u00a0=<>\"\'\/?]/);return"word"}function U(c){return function(g,h){for(;!g.eol();)if(g.next()==c){h.tokenize=C;break}return"string"}}function ba(c,g){return function(h,q){for(;!h.eol();){if(h.match(g)){q.tokenize=
E;break}h.next()}return c}}function W(c){return function(g,h){for(var q;null!=(q=g.next());){if("<"==q)return h.tokenize=W(c+1),h.tokenize(g,h);if(">"==q)if(1==c){h.tokenize=E;break}else return h.tokenize=W(c-1),h.tokenize(g,h)}return"meta"}}function z(){for(var c=arguments.length-1;0<=c;c--)T.cc.push(arguments[c])}function h(){z.apply(null,arguments);return!0}function c(c){return"openTag"==c?(T.tagName=da,h(oa,g(T.startOfLine))):"closeTag"==c?(c=!1,(c=T.context?T.context.tagName!=da:!0)&&(w="error"),
h(ga(c))):h()}function g(c){return function(g){if("selfcloseTag"==g||"endTag"==g&&$.autoSelfClosers.hasOwnProperty(T.tagName.toLowerCase()))return h();if("endTag"==g){g=T.tagName;var w=$.doNotIndent.hasOwnProperty(g)||T.context&&T.context.noIndent;T.context={prev:T.context,tagName:g,indent:T.indented,startOfLine:c,noIndent:w}}return h()}}function ga(c){return function(g){c&&(w="error");if("endTag"==g)return T.context&&(T.context=T.context.prev),h();w="error";return h(arguments.callee)}}function oa(c){return"word"==
c?(w="attribute",h(oa)):"equals"==c?h(L,oa):"string"==c?(w="error",h(oa)):z()}function L(c){return"word"==c&&$.allowUnquoted?(w="string",h()):"string"==c?h(G):z()}function G(c){return"string"==c?h(G):z()}var M=r.indentUnit,$=O.htmlMode?{autoSelfClosers:{br:!0,img:!0,hr:!0,link:!0,input:!0,meta:!0,col:!0,frame:!0,base:!0,area:!0},doNotIndent:{pre:!0},allowUnquoted:!0}:{autoSelfClosers:{},doNotIndent:{},allowUnquoted:!1},v=O.alignCDATA,da,K,T,w;return{startState:function(){return{tokenize:E,cc:[],indented:0,
startOfLine:!0,tagName:null,context:null}},token:function(g,h){g.sol()&&(h.startOfLine=!0,h.indented=g.indentation());if(g.eatSpace())return null;w=K=da=null;var v=h.tokenize(g,h);h.type=K;if((v||K)&&"comment"!=v)for(T=h;!(h.cc.pop()||c)(K||v););h.startOfLine=!1;return w||v},indent:function(c,g,h){var q=c.context;if(c.tokenize!=C&&c.tokenize!=E||q&&q.noIndent)return h?h.match(/^(\s*)/)[0].length:0;if(v&&/<!\[CDATA\[/.test(g))return 0;q&&/^<\//.test(g)&&(q=q.prev);for(;q&&!q.startOfLine;)q=q.prev;
return q?q.indent+M:0},compareStates:function(c,g){if(c.indented!=g.indented||c.tokenize!=g.tokenize)return!1;for(var h=c.context,q=g.context;;h=h.prev,q=q.prev){if(!h||!q)return h==q;if(h.tagName!=q.tagName)return!1}},electricChars:"/"}});CodeMirror.defineMIME("application/xml","xml");CodeMirror.defineMIME("text/html",{name:"xml",htmlMode:!0});
CodeMirror.defineMode("javascript",function(r,O){function E(c,g){for(var h=!1,a;null!=(a=c.next());){if(a==g&&!h)return!1;h=!h&&"\\"==a}return h}function C(c,g,h){xa=c;Pa=h;return g}function U(c,g){var h=c.next();if('"'==h||"'"==h)return h=ba(h),g.tokenize=h,h(c,g);if(/[\[\]{}\(\),;\:\.]/.test(h))return C(h);if("0"==h&&c.eat(/x/i))return c.eatWhile(/[\da-f]/i),C("number","number");if(/\d/.test(h))return c.match(/^\d*(?:\.\d*)?(?:[eE][+\-]?\d+)?/),C("number","number");if("/"==h){if(c.eat("*"))return h=
W,g.tokenize=h,h(c,g);if(c.eat("/"))return c.skipToEnd(),C("comment","comment");if(g.reAllowed)return E(c,"/"),c.eatWhile(/[gimy]/),C("regexp","string");c.eatWhile(aa);return C("operator",null,c.current())}if("#"==h)return c.skipToEnd(),C("error","error");if(aa.test(h))return c.eatWhile(aa),C("operator",null,c.current());c.eatWhile(/[\w\$_]/);var h=c.current(),a=Ma.propertyIsEnumerable(h)&&Ma[h];return a&&g.kwAllowed?C(a.type,a.style,h):C("variable","variable",h)}function ba(c){return function(g,
h){E(g,c)||(h.tokenize=U);return C("string","string")}}function W(c,g){for(var h=!1,a;a=c.next();){if("/"==a&&h){g.tokenize=U;break}h="*"==a}return C("comment","comment")}function z(c,g,h,a,b,d){this.indented=c;this.column=g;this.type=h;this.prev=b;this.info=d;null!=a&&(this.align=a)}function h(){for(var c=arguments.length-1;0<=c;c--)F.cc.push(arguments[c])}function c(){h.apply(null,arguments);return!0}function g(c){var g=F.state;if(g.context){F.marked="def";for(var h=g.localVars;h;h=h.next)if(h.name==
c)return;g.localVars={name:c,next:g.localVars}}}function ga(){F.state.context||(F.state.localVars=ua);F.state.context={prev:F.state.context,vars:F.state.localVars}}function oa(){F.state.localVars=F.state.context.vars;F.state.context=F.state.context.prev}function L(c,g){var h=function(){var a=F.state;a.lexical=new z(a.indented,F.stream.column(),c,null,a.lexical,g)};h.lex=!0;return h}function G(){var c=F.state;c.lexical.prev&&(")"==c.lexical.type&&(c.indented=c.lexical.indented),c.lexical=c.lexical.prev)}
function M(e){return function(g){return g==e?c():";"==e?h():c(arguments.callee)}}function $(e){return"var"==e?c(L("vardef"),q,M(";"),G):"keyword a"==e?c(L("form"),v,$,G):"keyword b"==e?c(L("form"),$,G):"{"==e?c(L("}"),R,G):";"==e?c():"function"==e?c(Ka):"for"==e?c(L("form"),M("("),L(")"),ka,M(")"),G,$,G):"variable"==e?c(L("stat"),T):"switch"==e?c(L("form"),v,L("}","switch"),M("{"),R,G,G):"case"==e?c(v,M(":")):"default"==e?c(M(":")):"catch"==e?c(L("form"),ga,M("("),va,M(")"),$,G,oa):h(L("stat"),v,
M(";"),G)}function v(e){return Ca.hasOwnProperty(e)?c(K):"function"==e?c(Ka):"keyword c"==e?c(da):"("==e?c(L(")"),v,M(")"),G,K):"operator"==e?c(v):"["==e?c(L("]"),N(v,"]"),G,K):"{"==e?c(L("}"),N(A,"}"),G,K):c()}function da(c){return c.match(/[;\}\)\],]/)?h():h(v)}function K(e,g){if("operator"==e&&/\+\+|--/.test(g))return c(K);if("operator"==e)return c(v);if(";"!=e){if("("==e)return c(L(")"),N(v,")"),G,K);if("."==e)return c(w,K);if("["==e)return c(L("]"),v,M("]"),G,K)}}function T(e){return":"==e?c(G,
$):h(K,M(";"),G)}function w(e){if("variable"==e)return F.marked="property",c()}function A(e){"variable"==e&&(F.marked="property");if(Ca.hasOwnProperty(e))return c(M(":"),v)}function N(e,g){function q(a){return","==a?c(e,q):a==g?c():c(M(g))}return function(a){return a==g?c():h(e,q)}}function R(e){return"}"==e?c():h($,R)}function q(e,h){return"variable"==e?(g(h),c(ha)):c()}function ha(e,g){if("="==g)return c(v,ha);if(","==e)return c(q)}function ka(e){return"var"==e?c(q,ta):";"==e?h(ta):"variable"==
e?c(qb):h(ta)}function qb(e,g){return"in"==g?c(v):c(K,ta)}function ta(e,g){return";"==e?c(Na):"in"==g?c(v):c(v,M(";"),Na)}function Na(e){")"!=e&&c(v)}function Ka(e,h){if("variable"==e)return g(h),c(Ka);if("("==e)return c(L(")"),ga,N(va,")"),G,$,oa)}function va(e,h){if("variable"==e)return g(h),c()}var X=r.indentUnit,Qa=O.json,Ma=function(){function c(a){return{type:a,style:"keyword"}}var g=c("keyword a"),h=c("keyword b"),a=c("keyword c"),b=c("operator"),d={type:"atom",style:"atom"};return{"if":g,
"while":g,"with":g,"else":h,"do":h,"try":h,"finally":h,"return":a,"break":a,"continue":a,"new":a,"delete":a,"throw":a,"var":c("var"),"const":c("var"),let:c("var"),"function":c("function"),"catch":c("catch"),"for":c("for"),"switch":c("switch"),"case":c("case"),"default":c("default"),"in":b,"typeof":b,"instanceof":b,"true":d,"false":d,"null":d,undefined:d,NaN:d,Infinity:d}}(),aa=/[+\-*&%=<>!?|]/,xa,Pa,Ca={atom:!0,number:!0,variable:!0,string:!0,regexp:!0},F={state:null,column:null,marked:null,cc:null},
ua={name:"this",next:{name:"arguments"}};G.lex=!0;return{startState:function(c){return{tokenize:U,reAllowed:!0,kwAllowed:!0,cc:[],lexical:new z((c||0)-X,0,"block",!1),localVars:null,context:null,indented:0}},token:function(c,g){c.sol()&&(g.lexical.hasOwnProperty("align")||(g.lexical.align=!1),g.indented=c.indentation());if(c.eatSpace())return null;var h=g.tokenize(c,g);if("comment"==xa)return h;g.reAllowed="operator"==xa||"keyword c"==xa||xa.match(/^[\[{}\(,;:]$/);g.kwAllowed="."!=xa;a:{var a=xa,
b=Pa,d=g.cc;F.state=g;F.stream=c;F.marked=null;F.cc=d;g.lexical.hasOwnProperty("align")||(g.lexical.align=!0);for(;;)if((d.length?d.pop():Qa?v:$)(a,b)){for(;d.length&&d[d.length-1].lex;)d.pop()();if(F.marked){h=F.marked;break a}if(a="variable"==a)b:{for(a=g.localVars;a;a=a.next)if(a.name==b){a=!0;break b}a=void 0}if(a){h="variable-2";break a}break a}h=void 0}return h},indent:function(c,g){if(c.tokenize!=U)return 0;var h=g&&g.charAt(0),a=c.lexical,b=a.type,d=h==b;return"vardef"==b?a.indented+4:"form"==
b&&"{"==h?a.indented:"stat"==b||"form"==b?a.indented+X:"switch"!=a.info||d?a.align?a.column+(d?0:1):a.indented+(d?0:X):a.indented+(/^(?:case|default)\b/.test(g)?X:2*X)},electricChars:":{}"}});CodeMirror.defineMIME("text/javascript","javascript");CodeMirror.defineMIME("application/json",{name:"javascript",json:!0});
CodeMirror.defineMode("css",function(r){function O(h,c){z=c;return h}function E(h,c){var g=h.next();if("@"==g)return h.eatWhile(/[\w\\\-]/),O("meta",h.current());if("/"==g&&h.eat("*"))return c.tokenize=C,C(h,c);if("<"==g&&h.eat("!"))return c.tokenize=U,U(h,c);if("="==g)O(null,"compare");else{if("~"!=g&&"|"!=g||!h.eat("=")){if('"'==g||"'"==g)return c.tokenize=ba(g),c.tokenize(h,c);if("#"==g)return h.eatWhile(/[\w\\\-]/),O("atom","hash");if("!"==g)return h.match(/^\s*\w*/),O("keyword","important");
if(/\d/.test(g))return h.eatWhile(/[\w.%]/),O("number","unit");if(/[,.+>*\/]/.test(g))return O(null,"select-op");if(/[;{}:\[\]]/.test(g))return O(null,g);h.eatWhile(/[\w\\\-]/);return O("variable","variable")}return O(null,"compare")}}function C(h,c){for(var g=!1,r;null!=(r=h.next());){if(g&&"/"==r){c.tokenize=E;break}g="*"==r}return O("comment","comment")}function U(h,c){for(var g=0,r;null!=(r=h.next());){if(2<=g&&">"==r){c.tokenize=E;break}g="-"==r?g+1:0}return O("comment","comment")}function ba(h){return function(c,
g){for(var r=!1,z;null!=(z=c.next())&&(z!=h||r);)r=!r&&"\\"==z;r||(g.tokenize=E);return O("string","string")}}var W=r.indentUnit,z;return{startState:function(h){return{tokenize:E,baseIndent:h||0,stack:[]}},token:function(h,c){if(h.eatSpace())return null;var g=c.tokenize(h,c),r=c.stack[c.stack.length-1];"hash"==z&&"rule"==r?g="atom":"variable"==g&&("rule"==r?g="number":r&&"@media{"!=r||(g="tag"));"rule"==r&&/^[\{\};]$/.test(z)&&c.stack.pop();"{"==z?"@media"==r?c.stack[c.stack.length-1]="@media{":c.stack.push("{"):
"}"==z?c.stack.pop():"@media"==z?c.stack.push("@media"):"{"==r&&"comment"!=z&&c.stack.push("rule");return g},indent:function(h,c){var g=h.stack.length;/^\}/.test(c)&&(g-="rule"==h.stack[h.stack.length-1]?2:1);return h.baseIndent+g*W},electricChars:"}"}});CodeMirror.defineMIME("text/css","css");
CodeMirror.defineMode("htmlmixed",function(r,O){function E(c,g){var r=W.token(c,g.htmlState);"tag"==r&&(">"==c.current()&&g.htmlState.context)&&(/^script$/i.test(g.htmlState.context.tagName)?(g.token=U,g.localState=z.startState(W.indent(g.htmlState,"")),g.mode="javascript"):/^style$/i.test(g.htmlState.context.tagName)&&(g.token=ba,g.localState=h.startState(W.indent(g.htmlState,"")),g.mode="css"));return r}function C(c,g,h){var r=c.current();g=r.search(g);-1<g&&c.backUp(r.length-g);return h}function U(c,
g){return c.match(/^<\/\s*script\s*>/i,!1)?(g.token=E,g.curState=null,g.mode="html",E(c,g)):C(c,/<\/\s*script\s*>/,z.token(c,g.localState))}function ba(c,g){return c.match(/^<\/\s*style\s*>/i,!1)?(g.token=E,g.localState=null,g.mode="html",E(c,g)):C(c,/<\/\s*style\s*>/,h.token(c,g.localState))}var W=CodeMirror.getMode(r,{name:"xml",htmlMode:!0}),z=CodeMirror.getMode(r,"javascript"),h=CodeMirror.getMode(r,"css");return{startState:function(){var c=W.startState();return{token:E,localState:null,mode:"html",
htmlState:c}},copyState:function(c){if(c.localState)var g=CodeMirror.copyState(c.token==ba?h:z,c.localState);return{token:c.token,localState:g,mode:c.mode,htmlState:CodeMirror.copyState(W,c.htmlState)}},token:function(c,g){return g.token(c,g)},indent:function(c,g){return c.token==E||/^\s*<\//.test(g)?W.indent(c.htmlState,g):c.token==U?z.indent(c.localState,g):h.indent(c.localState,g)},compareStates:function(c,g){return W.compareStates(c.htmlState,g.htmlState)},electricChars:"/{}:"}});
CodeMirror.defineMIME("text/html","htmlmixed");
